### ISSUE TITLE
Best practice of mdbx_txn_commit()

### ISSUE THREAD

**Issue by wangjia184** [leo-yuriev/libmdbx#44]
It turns out `mdbx_txn_commit()` is the most IO-bound operation. In my machine it takes 200-300ms  even there is only one `mdbx_put` in each txn.

I want the changes are accumulated in a single txn, and txn is not commited until `mdbx_put` cannt put more changes.

```
int err = mdbx_put(txn, dbi, key, value, 0);
if( MDBX_TXN_FULL == err || MDBX_MAP_FULL == err  ) {
     mdbx_txn_commit(txn);  // now commit the transaction
     mdbx_txn_begin( env, NULL, 0, &tnx); // start a new transaction 
     mdbx_put(txn, dbi, key, value, 0); // add the failed one and it will be commited when MDBX_TXN_FULL 
 or MDBX_MAP_FULL occurs again
}
```

But `mdbx_txn_commit` fails with error `MDBX_BAD_TXN`

**Comment by leo-yuriev** [comment]
Yes, of cause `mdbx_txn_commit()` will be always the mostly IO-heavy operation, since only commit will persist any changes on a disk.

Internally libmdbx uses a list of pages to tracking a 'dirty' pages, which should be updated on the disk during transaction commit. This list couldn't be boundless, therefore libmdbx has a reasonable [internal limit](https://github.com/leo-yuriev/libmdbx/blob/d2bfb2e489d05977b195219fafb628dbf18778f3/src/bits.h#L528-L530), actualy 4194304 pages. When this limit reached the transaction will be marked as broken and should be aborted.
Currently I assume no other reasonable options for this behavior.

With "fill level" of transaction you will be able to create the "largest possible" transaction, that will use a lot of RAM and will require an EVENT MORE I/O during commit. But no reason to do this, since you may use batching up to 1000-100000 updates per transaction.
