### ISSUE TITLE
Setup CD to build libmdbx for mainstream platforms

### ISSUE THREAD

**Issue by wangjia184** [leo-yuriev/libmdbx#46]
[mdbx.NET](https://github.com/wangjia184/mdbx.NET) ships libmdbx binaries along with its package management. mdbx.NET is a .NET Standard assembly and it is compatible for Linux/Mac as well. When mdbx.NET starts, it checks OS type and loads corresponding edition binary automatically. Hence its user does not care about deployment at all.

In this reason, mdbx.NET needs to embed libmdbx binaries of mainstream platforms. e.g Mac OS / Windows / Linux distributions (Debian / CentOS / Alpine). Currently I only build libmdbx for Windows x64/x86 platform manually. I want to include other platforms but that would cost a lot of time to build libmdbx on all the platforms. And that is not a one-time job.  

It is better to have some automatic CI process to build libmdbx on each platform in docker container and binaries are provided directly in release section of GitHub.

**Comment by leo-yuriev** [comment]
Thank you for .NET bindings.

1. libmdbx yiet not support Mac OC.
2. I do not plan to distribute anything other than the source code in the near future.
3. I think you should not include anyone binary DLLs into your source code.
Instead of this you should just add to your `mdbx.sln` a dependency from my dll-project (the `dll.vcxproj` file). I assume this will be is enough.

**Comment by leo-yuriev** [comment]
Continuous Integration (aka CI) for (all supported platforms) is done more than year ago.
Continuous Delivery (aka CD) is not a goal, since `libmdbx` now provided in source code only, but not in binary/packaged form.

It is planned to provide packages for common Linux distributions, but not any binary builds for Windows (
at least until Microsoft provides the appropriate infrastructure, which is unexpected and unlikely).
