### ISSUE TITLE
FeatureRequest: OSX support

### ISSUE THREAD

**Issue by alexdovzhanyn** [leo-yuriev/libmdbx#49]
I'm really excited about this project, it looks very promising, and my team and I are looking into building elixir/erlang bindings for this, but I'm having trouble compiling for OSX and I saw you mentioned in another issue that there is no OSX support yet.

Is there a timeline or an estimate as to when you're planning to make this OSX compatible?

**Comment by leo-yuriev** [comment]
I don't use a Mac myself and there were no other good reasons to implement OSX support.

OSX support can be technically very simple or quite challenging. To do this, we need to know all the subtleties of the corresponding API: file and other locks, shared mutexes, memory-mapped files with changing size of ones, initialization and finalization of thread local storage.

In the case of Windows, it was very difficult. It took a long time and brought enough regressions.
I would never do that, but it was demanded by the business of the company where I work now.

I do not plan to implement support for OSX by myself. Since this requires not only time (ie, abandonment implementation of other MDBX' features), and the purchase of a Mac (which is useless for me).
However, I think I can find time for a code review of your implementation, unless of course if you'll take this upon yourself.

**Comment by alexdovzhanyn** [comment]
Thanks for the reply! We'll take a look at adding OSX support, I have a mac so I can take a look. At first glance I was able to get it mostly compiled -- outside of some atom reference issues.

**Comment by bertbeck** [comment]
I am also interested in OSX support. Any progress? I could help as well.

**Comment by alexdovzhanyn** [comment]
@bertbeck I looked into it a bit but never got around to implementing. That being said we have been looking for someone to join our team specifically to work on this as a feature, so if that interests you let me know and we can talk further!

**Comment by bertbeck** [comment]
I’m Interested!
How much time did you think it would take?
Who is your team?

**Comment by alexdovzhanyn** [comment]
We've been looking for a C dev to add OSX support and unfortunately
everyone else is on Linux. If you have experience working with C and can
look into adding support we'd donate towards your effort

**Comment by bertbeck** [comment]
I am a C and DB developer. Tell me me more about what you could provide.
I’m looking for a very fast and robust database- interested also in seeing
if hashed keyed access could be added

Do you use libmdbx in production? How reliable is it?

**Comment by alexdovzhanyn** [comment]
@bertbeck We haven't been able to use it in production due to the lack of MacOS support. @leo-yuriev might be a better resource to answer this question. If you want to look into adding MacOS support to it we can donate some Bitcoin to your efforts.

**Comment by bertbeck** [comment]
ok

do you use libmdbx in production? How reliable is it?

**Comment by alexdovzhanyn** [comment]
@bertbeck 





> We haven't been able to use it in production due to the lack of MacOS support

**Comment by bertbeck** [comment]
I see.

**Comment by leo-yuriev** [comment]
Partially done in the 'osx-try' branch.
I will continue (e.g. debug it by kvm) in a weekend.

**Comment by alexdovzhanyn** [comment]
@leo-yuriev That's great, very excited for this!

**Comment by leo-yuriev** [comment]
With great difficulty (thanks to Apple) I managed to install Mojave in VirtualBox.
So, the code in the 'osx-try' branch compiles (just by `make`) without warnings and works (for instance `make test`).

However, compared to Linux and FreeBSD, tests are much slower (20-30 times) even when text data is placed in ramfs. This causes the tests to be timed out on travis-ci.org
The top utility shows about that 5-10% of time spent in the user mode and 50-60% in the kernel mode.

Currently I have no ideas what can be improved. Nevertheless maybe next weekend (or even earlier) I will have time to compare the performance of libmdbx and LMDB in ioarena tests under VirtualBox.
It is highly likely that the difference will not be, otherwise I'll be figure it out.

Anyway you can try it and give me a feedback.

**Comment by alexdovzhanyn** [comment]
I'll play around with it this week! Aiming to add binding support for
elixir.

**Comment by leo-yuriev** [comment]
I measured the performance by [ioarena](https://github.com/pmwkaa/ioarena) tests under VirtualBox.
**Briefly:**
 - libmdbx is a little bit faster than LMDB (details are below).
 - Data durability [requires](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fsync.2.html) `fcntl(F_FULLFSYNC)` instead of `fsync()`.
 - **_But_** using `fcntl(F_FULLFSYNC)` (see this [commit](https://github.com/leo-yuriev/libmdbx/commit/226cb3ac90720cd39167e627d2018487e1d2b0a1)) show slowdown 5-10 times.
 - Q: What is better speed or durability?
   It is certainly rhetorical. I will add a build option.

---

libmdbx:
```
../ioarena/@BUILD/src/ioarena -D mdbx -B crud -m sync -n 250000 | tee bench-mdbx_250000.txt | grep throughput \
&& ../ioarena/@BUILD/src/ioarena -D mdbx -B get,iterate -m sync -r 4 -n 250000 | tee -a bench-mdbx_250000.txt | grep throughput
 throughput:   1.842Kops/s
 throughput: 952.692Kops/s
 throughput: 804.865Kops/s
```
LMDB:
```
../ioarena/@BUILD/src/ioarena -D lmdb -B crud -m sync -n 250000 | tee bench-lmdb_250000.txt | grep throughput \
&& ../ioarena/@BUILD/src/ioarena -D lmdb -B get,iterate -m sync -r 4 -n 250000 | tee -a bench-lmdb_250000.txt | grep throughput
 throughput:   1.680Kops/s
 throughput: 945.821Kops/s
 throughput: 798.879Kops/s
```
Build ioarena with `cmake -DENABLE_LMDB=ON -DENABLE_MDBX=ON`, but few tricks are required:
 - change `SOEXT = .so` to `SOEXT = .dylib` in LMDB's makefile.
 - seek libmdbx submodule to `osx-try` branch.
 - make symlinks to `libmdbx.dylib` and `liblmdb.dylib` in the ioarena executable dir.

**Comment by leo-yuriev** [comment]
[Added](https://github.com/leo-yuriev/libmdbx/commit/657d37c9e39c647e0d8076b9b0ee9e0b2afeee88) `MDBX_OSX_SPEED_OR_DURABILITY` option.

```
#define MDBX_OSX_WANNA_DURABILITY 0 /* using fcntl(F_FULLFSYNC) with 5-10 times slowdown */
#define MDBX_OSX_WANNA_SPEED 1      /* using fsync() with chance of data lost on power failure */
#ifndef MDBX_OSX_SPEED_OR_DURABILITY
#define MDBX_OSX_SPEED_OR_DURABILITY MDBX_OSX_WANNA_DURABILITY
#endif
```
