### ISSUE TITLE
PVS Studio report

### ISSUE THREAD

**Issue by pavel-pimenov** [leo-yuriev/libmdbx#52]
PVS-Studio Version:	7.01.31225.1583
Total Warnings (GA):	106
Total Warnings (OP):	9
Total Warnings (64):	32

http://www.fly-server.ru/pvs-studio/libmdbx/

**Comment by leo-yuriev** [comment]
@pavel-pimenov, thank you for your work.
Unfortunately I won't be able to use the result.

PVS is a good statistical analyzer, but so far it is significantly inferior to Coverity in terms of practical use in open source projects:
- All statistical analyzers have to be pedantic, so they give a lot of false-positive warnings, especially for low-level "unsafe" C code.
- Therefore, it becomes important not only to identify suspicious constructs in the code, but also to provide support for the "life cycle" of generated warnings, ranging from expert classification (screening out false positives) to re-validation after changes are made.
- ["Coverity Scan"](https://scan.coverity.com/) provides dashboard where all the necessary functionality is put together, including: obtaining a license, integration with github and travis-ci.org, full automation of inspections and lifecycle management of detected defects. There are no such opportunities in PVS yet and everything has to be done manually.

Simply put, the warnings received from PVS look false-positive, but there is no way to save the result of their classification for reuse. Therefore, re-check, including after any source code changes, will re-require manual classification and comparison with the results of previous checks. Again and again...

Moreover, it is not possible to discuss publicly the defects received from PVS, to show the results of the classification of these defects and the results of the check aftre such classification (after screening false positives).

In other words, if I decide to use the results of such checks and make any changes to the source code, then the result of this work cannot be shown in a reasonable way and/or (re)checked. Therefore, we can say that when using PVS, everything will be boils down to trusting my words "there are no bugs here, but this is not accurate".

So, since we already have CoveryScan-backed analysis, I just like to say "there are no bugs here..." ;)
@SvyatoslavRazmyslov, @skhrenov: FYI.

P.S.
One of the important features of CoveryScan is that once a defect classification is made, it is taken into account in derivative projects. For instance, the results of analysis and classification of coverity defects within libmdbx are automatically taken into account in [libfpta](https://github.com/PositiveTechnologies/libfpta), where libmdbx is used as a sub-project.

**Comment by SvyatoslavRazmyslov** [comment]
@leo-yuriev thank you for your comment.

For many years, there has been the possibility of suppressing FA warnings. See the article "[How to Step Over Legacy and Start Using Static Code Analysis](https://www.viva64.com/en/b/0527/)".
